# ── Compute Writer ────────────────────────────────────────────────────────────
#
# Write lines.computed.json from validated topology + computed chains + geometry.
#
# See: compute/README.md

require 'json'

module JPods
  module Compute
    module Writer

      def self.write(model_id, template_data, geometry_result)
        plugin_dir = File.dirname(File.dirname(__FILE__))
        out_path = File.join(plugin_dir, 'templates', 'track_formations',
                             model_id, 'lines.computed.json')

        nat = template_data['natalie'] || {}
        des = template_data['designer'] || {}
        designer_tracks = des['tracks'] || {}
        tracks = geometry_result[:tracks]

        # Build geometry section
        geo_tracks = {}
        tracks.each do |tag, td|
          pts = td['pts_mm']
          # Direction vector — authoritative flow direction from the centerline math.
          # Computed from first two points. Natalie uses this instead of guessing.
          dir = nil
          if pts.is_a?(Array) && pts.size >= 2
            p0 = pts[0]; p1 = pts[1]
            dx = p1[0].to_f - p0[0].to_f
            dy = p1[1].to_f - p0[1].to_f
            dz = p1[2].to_f - p0[2].to_f
            mag = Math.sqrt(dx*dx + dy*dy + dz*dz)
            if mag > 0.001
              dir = { 'x' => (dx/mag).round(6), 'y' => (dy/mag).round(6), 'z' => (dz/mag).round(6) }
            end
          end

          # Successors from lines.json — human-readable topology alongside the points.
          # Users can't read coordinate arrays, but they can read "gw_cp_in_0 → gw_in_0".
          succs = designer_tracks.dig(tag, 'successors')

          entry = {
            'pts_mm'    => pts,
            'length_mm' => td['length_mm'],
            'radius_mm' => td['radius_mm'] || 0.0,
            'direction' => dir,
          }
          entry['successors'] = succs if succs.is_a?(Array)
          geo_tracks[tag] = entry
        end

        # Build CP markers section from noelle.cps if available
        cp_markers = {}
        Array(des['cps']).each_with_index do |ep, _i|
          # CP markers from geometry_local if available
        end
        geo_local = des.dig('geometry_local', 'cp_markers') || {}

        has_platform = geo_tracks.key?('gw_platform')

        output = {
          'schema_version' => '2.0',
          'model_id'       => model_id,
          'has_platform'   => has_platform,
          'generated_at'   => Time.now.utc.strftime('%Y-%m-%dT%H:%M:%SZ'),
          'generated_by'   => 'JPods::Compute v2',
          'approved_at'    => nil,
          'test_results'   => {},
          'source_files'   => _source_file_stamps(plugin_dir, model_id),
          'note'           => 'Generated by three-phase Compute pipeline. Math only, no edge walking.',
          'geometry' => {
            'tracks'     => geo_tracks,
            'cp_markers' => geo_local,
          },
          'natalie' => nat,
          'cp'      => template_data.dig('noelle', 'cps') || des['cps'] || [],
          'feature' => template_data.dig('noelle', 'required_tracks') ?
                         { 'required_tracks' => template_data.dig('noelle', 'required_tracks') } : {},
        }

        # Embed chain lengths
        chain_lengths = {}
        (nat['landing_chains'] || {}).each do |key, chain|
          next if key == 'note'
          chain_tracks = Array(chain['tracks'])
          len = chain_tracks.sum { |t| (tracks.dig(t, 'length_mm') || 0).to_f }
          chain_lengths["landing.#{key}"] = len.round(1)
        end
        (nat['exit_chains'] || {}).each do |key, chain|
          next if key == 'note'
          chain_tracks = Array(chain['tracks'])
          len = chain_tracks.sum { |t| (tracks.dig(t, 'length_mm') || 0).to_f }
          chain_lengths["exit.#{key}"] = len.round(1)
        end
        output['chain_lengths_mm'] = chain_lengths unless chain_lengths.empty?

        # Track length summary
        track_lengths = {}
        geo_tracks.each { |tag, td| track_lengths[tag] = td['length_mm'] }
        output['track_lengths_mm'] = track_lengths

        File.write(out_path, JSON.pretty_generate(output), encoding: 'utf-8')
        puts "[Compute] lines.computed.json written — #{model_id} " \
             "(#{geo_tracks.size} tracks, #{chain_lengths.size} chains)"
        out_path
      end

      # Record mtime of each source file at Compute time.
      # check_approval compares these against approved_at —
      # any file saved after approval invalidates the model.
      def self._source_file_stamps(plugin_dir, model_id)
        tmpl_dir = File.join(plugin_dir, 'templates', 'track_formations', model_id)
        stamps = {}
        %w[model.skp lines.json].each do |fname|
          path = File.join(tmpl_dir, fname)
          if File.exist?(path)
            stamps[fname] = File.mtime(path).utc.strftime('%Y-%m-%dT%H:%M:%SZ')
          end
        end
        stamps
      end

    end
  end
end
