# jpod_project.rb — Project path helpers for the JPods plugin
#
# JPods::Project resolves canonical file paths for all artifacts beside
# the .skp file:
#   <base>.followme.json   — network_definition authoring + runtime export
#   <base>.vehicles.json   — vehicle placement plan
#   <base>.map.json        — generated route graph
#   README.md              — human-readable project folder summary
#
# Also manages the skp_jpods folder structure and first-run setup agreement.
#
# These helpers were extracted from JPods::NetworkEditor so every module
# can resolve paths without depending on the editor dialog.
#
# All callers that previously used JPods::NetworkEditor.project_dir (etc.)
# continue to work — NetworkEditor keeps 1-line delegation stubs.

require 'json'
require 'fileutils'
require 'shellwords'

module JPods
  module Project

    # Fallback staging folder for unsaved models.
    remove_const(:LIBRARY_DIR) if const_defined?(:LIBRARY_DIR)
    LIBRARY_DIR = File.join(Dir.home, "Documents", "JPods Networks").freeze

    def self.library_dir
      Dir.mkdir(LIBRARY_DIR) unless Dir.exist?(LIBRARY_DIR)
      LIBRARY_DIR
    rescue => e
      puts "JPods Project: cannot create library dir: #{e.message}"
      Dir.home
    end

    # Base filename without extension.  "untitled" for unsaved models.
    def self.project_base_name(model)
      model.path && !model.path.empty? ?
        File.basename(model.path, File.extname(model.path)) :
        "untitled"
    end

    # Folder where all project artifacts live.
    # Saved model → beside the .skp.
    # Unsaved model → ~/Documents/JPods Networks/<name>/
    def self.project_dir(model)
      if model.path && !model.path.empty?
        File.dirname(model.path)
      else
        dir = File.join(library_dir, project_base_name(model))
        Dir.mkdir(dir) unless Dir.exist?(dir)
        dir
      end
    rescue => e
      puts "JPods Project: cannot resolve project dir: #{e.message}"
      library_dir
    end

    # Feature JSON path — source of truth for user-drawn cp_ connections and
    # Noelle station behaviors. Written by Connect tool; enriched by Noelle after build.
    def self.default_network_json_path(model)
      File.join(project_dir(model), "#{project_base_name(model)}.network.json")
    end

    # FollowMe JSON path — internal build artifact (geometry, routing graph).
    # Not user-facing. Generated by the build pipeline; read by Natalie/validator.
    def self.default_json_path(model)
      File.join(project_dir(model), "#{project_base_name(model)}.followme.json")
    end

    # Route graph JSON path — Nora's flat seg_ navigation map. Generated by Noelle after build.
    def self.default_map_json_path(model)
      File.join(project_dir(model), "#{project_base_name(model)}.map.json")
    end

    # Vehicle placement plan JSON path.
    def self.default_vehicle_json_path(model)
      File.join(project_dir(model), "#{project_base_name(model)}.vehicles.json")
    end

    # Build log JSON path — written after every Build.
    def self.build_log_path(model)
      File.join(project_dir(model), "#{project_base_name(model)}.build.log.json")
    end

    # Route log JSON path — rolling log, appended after every Show Route.
    def self.route_log_path(model)
      File.join(project_dir(model), "#{project_base_name(model)}.route.log.json")
    end

    # Write (or overwrite) the build log with a structured record of this Build run.
    def self.write_build_log(model, data)
      path = build_log_path(model)
      File.write(path, JSON.pretty_generate(data), encoding: 'utf-8')
      puts "[JPods Log] build log → #{File.basename(path)}"
    rescue => ex
      puts "[JPods Log] build log write failed: #{ex.message}"
    end

    # Append a route trip record to the rolling route log (keeps last 20).
    def self.append_route_log(model, trip_json)
      path = route_log_path(model)
      existing = File.exist?(path) ? (JSON.parse(File.read(path, encoding: 'utf-8')) rescue []) : []
      existing = existing.last(19) if existing.size >= 20
      existing << trip_json
      File.write(path, JSON.pretty_generate(existing), encoding: 'utf-8')
      puts "[JPods Log] route log → #{File.basename(path)} (#{existing.size} route#{'s' if existing.size != 1})"
    rescue => ex
      puts "[JPods Log] route log write failed: #{ex.message}"
    end

    # Human-readable README path.
    def self.project_readme_path(model)
      File.join(project_dir(model), "README.md")
    end

    # Write (or overwrite) a README summarising the project folder contents.
    def self.ensure_project_readme(model)
      base     = project_base_name(model)
      skp_name = model.path && !model.path.empty? ? File.basename(model.path) : "#{base}.skp"

      body = <<~MD
        # JPods Project Folder

        This folder keeps the SketchUp model and its related JPods JSON files together.

        Files:
        - `#{skp_name}` — SketchUp model.
        - `#{base}.followme.json` — canonical FollowMe file containing `network_definition` authoring JSON and exported runtime lines.
        - `#{base}.vehicles.json` — vehicle placement plan from the Vehicles panel.
        - `#{base}.map.json` — generated route graph for runtime and diagnostics.
        - `#{base}.route-diagnostics.json` — current routing snapshot for support and analysis.
        - `#{base}.console-log.json` — optional project-scoped standalone JSON log written only when console logging is enabled.

        Notes:
        - `#{base}.followme.json` is the source network design and runtime export.
        - `#{base}.vehicles.json` stores requested vehicle types, quantities, and speed.
        - `#{base}.map.json` is generated from built guideways and should not replace FollowMe.
        - Route diagnostics files are safe to share with support tools such as Allie and Copilot.
      MD

      File.write(project_readme_path(model), body, encoding: 'utf-8')
      true
    rescue => e
      puts "JPods Project: README write warning: #{e.message}"
      false
    end

    # ── skp_jpods folder setup and first-run agreement ──────────────────────────

    # Root of the managed project tree.
    remove_const(:SKP_JPODS_ROOT) if const_defined?(:SKP_JPODS_ROOT)
    SKP_JPODS_ROOT = File.join(Dir.home, 'Documents', 'skp_jpods').freeze

    SETUP_PREF_SECTION = 'JPods'.freeze
    SETUP_PREF_KEY     = 'skp_jpods_setup'.freeze

    # Possible values: nil (never asked), "offered_once", "agreed", "declined".
    def self.setup_status
      Sketchup.read_default(SETUP_PREF_SECTION, SETUP_PREF_KEY)
    end

    def self.setup_status=(val)
      Sketchup.write_default(SETUP_PREF_SECTION, SETUP_PREF_KEY, val.to_s)
    end

    def self.agreed?
      setup_status == 'agreed'
    end

    def self.declined?
      setup_status == 'declined'
    end

    # Offer the skp_jpods setup at the right moment.
    # trigger: :startup  — fires when status is nil (never asked)
    # trigger: :build    — fires when status is "offered_once"
    # Returns true if the user agreed (now or previously).
    def self.offer_setup(trigger:)
      status = setup_status
      return true  if status == 'agreed'
      return false if status == 'declined'
      return false if trigger == :startup  && !status.nil?
      return false if trigger == :build    && status != 'offered_once'

      if trigger == :startup
        msg = <<~MSG
          JPods recommends a standard folder for your project files:

            ~/Documents/skp_jpods/<ProjectName>/

          Each model, its network file (.followme.json), and all
          related files will be kept together in one named folder.
          A utilities/ folder will hold helper scripts.
          A README.md will explain the layout.

          YES  — Set up ~/Documents/skp_jpods/ now.
          NO   — Skip (JPods will ask once more when you build
                 your first network).
        MSG
        if UI.messagebox(msg, MB_YESNO) == IDYES
          perform_setup
          self.setup_status = 'agreed'
          true
        else
          self.setup_status = 'offered_once'
          false
        end

      else  # :build
        msg = <<~MSG
          This is your first JPods network build.

          JPods can organize your project files in:

            ~/Documents/skp_jpods/<ProjectName>/

          YES  — Set up ~/Documents/skp_jpods/ now.
          NO   — Manage files yourself.  JPods will record
                 your file locations in:
                 ~/Documents/skp_jpods/utilities/projects.json
        MSG
        if UI.messagebox(msg, MB_YESNO) == IDYES
          perform_setup
          self.setup_status = 'agreed'
          true
        else
          self.setup_status = 'declined'
          # Create just the utilities folder so the registry can be written.
          FileUtils.mkdir_p(File.join(SKP_JPODS_ROOT, 'utilities'))
          UI.messagebox(
            "No problem — you manage your own files.\n\n" \
            "JPods will keep a record of where your files are stored in:\n\n" \
            "  ~/Documents/skp_jpods/utilities/projects.json\n\n" \
            "The Finder button in the Network Editor can re-offer " \
            "this setup at any time.",
            MB_OK
          )
          false
        end
      end
    end

    # Create the full skp_jpods folder structure, write README and empty registry.
    def self.perform_setup
      utilities_dir  = File.join(SKP_JPODS_ROOT, 'utilities')
      readme_path    = File.join(SKP_JPODS_ROOT, 'README.md')
      registry_path  = File.join(utilities_dir,  'projects.json')

      FileUtils.mkdir_p(utilities_dir)
      File.write(readme_path,   skp_jpods_readme_text, encoding: 'utf-8') unless File.exist?(readme_path)
      File.write(registry_path, JSON.pretty_generate({}), encoding: 'utf-8') unless File.exist?(registry_path)

      UI.messagebox(
        "JPods project folder created:\n\n" \
        "  ~/Documents/skp_jpods/\n\n" \
        "Each project will live in its own subfolder.\n" \
        "See README.md in that folder for details.",
        MB_OK
      )
    rescue => e
      puts "JPods Project: perform_setup error: #{e.message}"
    end

    # Record a project that lives outside skp_jpods (status == "declined").
    # Safe to call from commit() or cmd_save — silently no-ops unless declined.
    def self.note_unmanaged_project(model)
      return unless declined?
      return unless model.path && !model.path.empty?

      utilities_dir = File.join(SKP_JPODS_ROOT, 'utilities')
      FileUtils.mkdir_p(utilities_dir)
      registry_path = File.join(utilities_dir, 'projects.json')

      registry = File.exist?(registry_path) ?
                   (JSON.parse(File.read(registry_path, encoding: 'utf-8')) rescue {}) : {}

      base = project_base_name(model)
      registry[base] = {
        'skp_path'      => model.path.to_s,
        'followme_path' => default_json_path(model),
        'noted_at'      => Time.now.utc.strftime('%Y-%m-%dT%H:%M:%SZ'),
      }
      File.write(registry_path, JSON.pretty_generate(registry), encoding: 'utf-8')
    rescue => e
      puts "JPods Project: note_unmanaged_project warning: #{e.message}"
    end

    # README written to ~/Documents/skp_jpods/ at first setup.
    def self.skp_jpods_readme_text
      <<~MD
        # skp_jpods — JPods Project Folder

        This folder is managed by the JPods SketchUp plugin.
        You agreed to let JPods organize your files here.

        ## Structure

            skp_jpods/
              README.md               ← this file
              utilities/
                projects.json         ← registry of all known projects
                organize.sh           ← last-used file-move script
              <ProjectName>/
                <ProjectName>.skp
                <ProjectName>.followme.json
                <ProjectName>.vehicles.json
                <ProjectName>.map.json
                trips/

        ## Rules

        - One subfolder per SketchUp model, named to match the .skp file.
        - The plugin creates the subfolder automatically when you first
          connect guideways in a model.
        - All files for a project stay together in its subfolder.
        - The utilities/ folder contains helper scripts generated by the
          plugin.  Do not run scripts from utilities/ manually unless you
          understand what they do.

        ## Changing your mind

        Click the Finder button in the JPods Network Editor at any time
        to reorganize a project or to re-run the setup.
      MD
    end

    # ── File collection and open-model location check ───────────────────────────

    # Returns every file/folder beside the model that belongs to this project.
    def self.collect_project_files(model)
      skp_path  = model.path.to_s
      return [] if skp_path.empty?
      base      = File.basename(skp_path, '.skp')
      model_dir = File.dirname(skp_path)
      found     = []

      found << skp_path if File.exist?(skp_path)
      backup = File.join(model_dir, "#{base}~.skp")
      found << backup if File.exist?(backup)

      %w[followme.json vehicles.json map.json].each do |suffix|
        f = File.join(model_dir, "#{base}.#{suffix}")
        found << f if File.exist?(f)
      end

      trips = File.join(model_dir, 'trips')
      found << trips if Dir.exist?(trips)

      found
    end

    # Called from the AppObserver when any model opens.
    # If the user has agreed to skp_jpods management and the model is outside
    # that folder, prompt to move it — deferred so the model fully loads first.
    def self.check_model_location_deferred(model)
      return unless agreed?

      UI.start_timer(1.5, false) do
        begin
          check_model_location(model)
        rescue => e
          puts "JPods Project: check_model_location error: #{e.message}"
        end
      end
    end

    # Returns true if the model has any JPods content — network attribute,
    # a followme.json beside it, or any entity with a JPods structure_id.
    # Used to skip the location prompt for non-JPods .skp files.
    def self.has_jpods_features?(model)
      return true if model.get_attribute('JPods', 'network_json_path')
      skp_path = model.path.to_s
      unless skp_path.empty?
        base      = File.basename(skp_path, '.skp')
        model_dir = File.dirname(skp_path)
        return true if File.exist?(File.join(model_dir, "#{base}.followme.json"))
      end
      model.entities.each do |e|
        next unless e.is_a?(Sketchup::ComponentInstance) || e.is_a?(Sketchup::Group)
        return true if e.get_attribute('JPods', 'structure_id')
      end
      false
    end

    # Creates a skeleton followme.json beside the .skp if one does not exist.
    # Called before collecting files for the organizer so the JSON is always
    # included in the move even when the student has not run Connect Guideways yet.
    def self.ensure_followme_json(model)
      return unless has_jpods_features?(model)
      # Never write into template folders — templates are read-only
      return if model.path.to_s.include?('track_formations')
      json_path = default_json_path(model)
      return if json_path.nil? || json_path.empty? || File.exist?(json_path)
      begin
        FileUtils.mkdir_p(File.dirname(json_path))
        skeleton = { 'network_definition' => { 'connections' => [] } }
        File.write(json_path, JSON.pretty_generate(skeleton), encoding: 'utf-8')
        puts "[JPods] created skeleton followme.json: #{json_path}"
      rescue => e
        puts "[JPods] could not create followme.json: #{e.message}"
      end
    end

    def self.check_model_location(model)
      skp_path = model.path.to_s
      return if skp_path.empty?                              # unsaved model
      return unless has_jpods_features?(model)               # not a JPods file
      model_dir = File.dirname(skp_path)
      return if model_dir.start_with?(SKP_JPODS_ROOT)       # already managed

      ensure_followme_json(model)                            # guarantee JSON exists before collect
      base       = File.basename(skp_path, '.skp')
      dest_dir   = File.join(SKP_JPODS_ROOT, base)
      candidates = collect_project_files(model)
      file_lines = candidates.map { |f|
        name = File.basename(f)
        File.directory?(f) ? "  #{name}/" : "  #{name}"
      }.join("\n")

      msg = <<~MSG
        This file is outside your skp_jpods folder:

          #{skp_path}

        Standard location:
          #{dest_dir}

        Files that will move:
        #{file_lines}

        YES    — Start the move. Then quit SketchUp (Cmd+Q).
                 Your model will reopen automatically from its new location.
        NO     — Quit SketchUp yourself and move the files manually.
        CANCEL — Keep working here for now.
      MSG

      result = UI.messagebox(msg, MB_YESNOCANCEL)

      case result
      when IDYES
        if defined?(JPods::NetworkEditor) &&
           JPods::NetworkEditor.respond_to?(:launch_organize_script)
          JPods::NetworkEditor.launch_organize_script(model, candidates, dest_dir)
        end
        # Remind the user to quit — the organize script is now running in the
        # background waiting for SketchUp to close.
        UI.messagebox(
          "Move queued.\n\nQuit SketchUp now (Cmd+Q) and your model will reopen automatically from:\n\n  #{dest_dir}",
          MB_OK, 'JPods — Quit to finish move'
        )
      end
      # CANCEL: do nothing — user keeps working
    end

    # ── JPods Save ───────────────────────────────────────────────────────────────
    #
    # Custom save that ensures the .skp and its JSON files live together in the
    # correct folder.  Called from the console Save button (cmd_jpods_save).
    #
    # Network models → ~/Documents/skp_jpods/<Name>/<Name>.skp
    # Template models → saved in place (already inside track_formations/)
    #
    # Returns a status message string for the console output strip.

    def self.jpods_save(model)
      return "No model open." unless model

      is_template = model.path.to_s.gsub('\\', '/').include?('track_formations')

      if is_template
        # Template: save in place
        if model.path.nil? || model.path.empty?
          return "Template has never been saved. Use File → Save As into templates/track_formations/<name>/model.skp"
        end
        model.save
        base_dir = File.dirname(model.path)
        return "✓ Template saved → #{File.basename(base_dir)}/#{File.basename(model.path)}"
      end

      # Network model
      if model.path.nil? || model.path.empty?
        # Never saved — prompt for a project name
        name = UI.inputbox(['Project name:'], [''], 'JPods — Save New Project')
        return "Save cancelled." unless name
        project_name = name[0].to_s.strip.gsub(/[^a-zA-Z0-9_\-]/, '_')
        return "Invalid name." if project_name.empty?

        dest_dir = File.join(SKP_JPODS_ROOT, project_name)
        FileUtils.mkdir_p(dest_dir)
        skp_path = File.join(dest_dir, "#{project_name}.skp")
        model.save(skp_path)
      else
        # Already saved — save in place, ensure folder exists
        dest_dir = File.dirname(model.path)
        FileUtils.mkdir_p(dest_dir)
        model.save
      end

      base = project_base_name(model)

      # Ensure associated JSON files exist (skeleton if new)
      ensure_followme_json(model)

      # Ensure network.json exists
      net_path = default_network_json_path(model)
      unless File.exist?(net_path)
        skeleton = { 'connections' => {} }
        File.write(net_path, JSON.pretty_generate(skeleton), encoding: 'utf-8')
      end

      # Ensure crew.json exists
      crew_path = File.join(dest_dir, "#{base}.crew.json")
      unless File.exist?(crew_path)
        File.write(crew_path, JSON.pretty_generate({}), encoding: 'utf-8')
      end

      # Ensure README exists
      ensure_project_readme(model)

      # Count what's in the folder
      files = Dir.glob(File.join(dest_dir, "#{base}.*"))
      "✓ Saved → #{base}/ (#{files.size} files)"

    rescue => e
      "Save failed: #{e.message}"
    end

    # ── End skp_jpods setup ──────────────────────────────────────────────────────

  end  # module Project
end  # module JPods
